name: Lock closed inactive issues

on:
  schedule:
    # Run at 16:00 every day
    - cron: '0 16 * * *'

jobs:
  lock_closed:
    if: github.repository == 'angular/angular'
    runs-on: ubuntu-latest
    steps:
      - uses: angular/dev-infra/github-actions/lock-closed@7ee6505210cff833b83ce05725368f74166c42f3
        with:
          lock-bot-key: ${{ secrets.LOCK_BOT_PRIVATE_KEY }}
